### PR TITLE
Nc shapefiles 

### PR DESCRIPTION
**Pull request by micahjohnson150**
Ok, I have added the commands to the makefiles to create the shapefiles from the netcdfs. 
Usage is `make nc_shapefiles`, assumes the topo.nc is underneath topo/. This will generate each subbasin shapefile from the topo as well as the basin_outline from the mask variable in the topo.nc

### CODE REVIEW

**Comment by scotthavens** [comment]
Are the outputs to the changes in the makefile somewhere we can view?

**Comment by micahjohnson150** [comment]
No, not yet. I was curious if you wanted them committed here or not.

**Comment by micahjohnson150** [comment]
Do you want them in /home/ops/gis to replace the others?

**Comment by scotthavens** [comment]
We probably don't need them committed but replacing the others in ops so we can check them out.

**Comment by micahjohnson150** [comment]
Ok. They're up. Take a look and make sure they are what is expected. If you unzip them in your downloads folder locally you can run qgis *.shp in the commandline and qgis will open with them all loaded.

**Comment by Hedrick-ARS** [comment]
Loaded all the shapefiles. They all look more like the nc files now. One thing is that the Tuolumne now has a weird file _50m.shp that is just a copy of the Cherry.shp file.

**Comment by micahjohnson150** [comment]
Nice catch @Hedrick-ARS . That was a little weird. I made the assumption when I wrote to a zip file it would overwrite it but I think the default was to overwrite files inside but not completely clear out the zip. I had seen it in my downloads but I assumed it was a file I forgot to delete. I updated it and repushed just the tuolumne  to /home/ops/gis

**Pull request merged**
